/**
 * Product represents a product entity in the database.
 */
namespace MiniEShopAPI.Models
{
    public class Product
    {
        public int Id { get; set; } // Id will be auto-generated by the database
        public string Name { get; set; } = string.Empty; // Name of the product
        public string Description { get; set; } = string.Empty; // Description of the product
        public decimal Price { get; set; } // Price of the product
    }
}